default: &default
  adapter: sqlserver
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: test
  password: testbattle
  host: LAPTOP-9RV10GJ7
  database: master

development:
  <<: *default
  database: master

test:
  <<: *default
  database: master

production:
  <<: *default
  database: master
