default: &default
  adapter: sqlserver
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: winner
  password: win1484
  host: LAPTOP-9RV10GJ7
  database: wins

development:
  <<: *default
  database: wins

test:
  <<: *default
  database: wins

production:
  <<: *default
  database: wins
